# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pocket-id-minimal
  labels:
    chart: pocket-id

spec:
  concurrent: true

  bindings:
    - name: arguments
      value: ''

  steps:
    - name: Install chart
      use:
        template: ../_lib/helm-install.yaml
        with:
          bindings:
            - name: arguments
              value: ($arguments)
            - name: namespace
              value: ($namespace)

    - name: Validate core instalation
      use:
        template: ../_lib/validate-core-installation.yaml
        with:
          bindings:
            - name: namespace
              value: ($namespace)
