apiVersion: v2
type: application
name: devenv
description: |
  Nix development environment pod with Tailscale SSH access and optional Docker-in-Docker.
home: https://github.com/anza-labs/charts
version: 0.1.2
appVersion: "latest"
sources:
  - https://github.com/anza-labs/charts
keywords:
  - nix
  - devpod
  - development
  - tailscale
  - dind
annotations:
  artifacthub.io/category: skip-prediction
  artifacthub.io/immutable: "true"
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
