apiVersion: v2
type: application
name: lubelogger
description: |
  LubeLogger is a web-based vehicle maintenance and fuel mileage tracker
home: https://lubelogger.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/lubelogger/icon.png
version: 1.4.5
appVersion: "v1.6.3"
sources:
  - https://github.com/hargata/lubelog
keywords:
  - vechicle
  - maintenance
  - dashboard
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/hargata/lubelogger docker tag to v1.6.3'
      links:
      - name: 'GitHub Issue #364'
        url: https://github.com/anza-labs/charts/issues/364
      - name: Commit 8b00f6f
        url: https://github.com/anza-labs/charts/commit/8b00f6f9530a716b147068d4c3f65bd5eb220f00
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
