apiVersion: v2
type: application
name: lubelogger
description: |
  LubeLogger is a web-based vehicle maintenance and fuel mileage tracker
home: https://lubelogger.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/lubelogger/icon.png
version: 1.4.3
appVersion: "v1.6.2"
sources:
  - https://github.com/hargata/lubelog
keywords:
  - vechicle
  - maintenance
  - dashboard
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/hargata/lubelogger docker tag to v1.6.1'
      links:
      - name: 'GitHub Issue #341'
        url: https://github.com/anza-labs/charts/issues/341
      - name: Commit f7d40ea
        url: https://github.com/anza-labs/charts/commit/f7d40eac9019d3d1cfb9100ff6ffdfb27f5dfcba
    - kind: changed
      description: '**deps:** update ghcr.io/hargata/lubelogger docker tag to v1.6.2'
      links:
      - name: 'GitHub Issue #349'
        url: https://github.com/anza-labs/charts/issues/349
      - name: Commit 05d2946
        url: https://github.com/anza-labs/charts/commit/05d2946a6d832de65c8f0ab8aca970d354a7b074
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
