apiVersion: v2
type: application
name: glauth
description: |
  glauth is a lightweight LDAP server for development, home use, or CI.
home: https://glauth.github.io
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/glauth/icon.png
version: 1.0.1
appVersion: "v2.4.0"
sources:
  - https://github.com/glauth/glauth
keywords:
  - idp
  - ldap
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/glauth/glauth docker tag to v2.5.2'
      links:
      - name: 'GitHub Issue #444'
        url: https://github.com/anza-labs/charts/issues/444
      - name: Commit bc58bb8
        url: https://github.com/anza-labs/charts/commit/bc58bb8cf252bd5dfc5e26c0e8431f4664a20076
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
