apiVersion: v2
type: application
name: glauth
description: |
  glauth is a lightweight LDAP server for development, home use, or CI.
home: https://glauth.github.io
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/glauth/icon.png
version: 1.0.2
appVersion: "v2.4.0"
sources:
  - https://github.com/glauth/glauth
keywords:
  - idp
  - ldap
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/glauth/glauth docker tag to v2.5.4'
      links:
      - name: 'GitHub Issue #471'
        url: https://github.com/anza-labs/charts/issues/471
      - name: Commit ef8890c
        url: https://github.com/anza-labs/charts/commit/ef8890c18f5831c828635d9bbf6304ec162aa0b0
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
