apiVersion: v2
type: application
name: registry
description: |-
  The Registry is a stateless, highly scalable server side application that
  stores and lets you distribute container images and other content.
home: https://distribution.github.io/distribution/
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/registry/icon.png
version: 1.0.3
appVersion: "3.1.0"
sources:
  - https://github.com/distribution/distribution
keywords:
  - oci-registry
  - docker
  - registry
  - distribution
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**install:** improve install docs'
      links:
      - name: 'GitHub Issue #399'
        url: https://github.com/anza-labs/charts/issues/399
      - name: Commit e8fdc56
        url: https://github.com/anza-labs/charts/commit/e8fdc5680642d4c2e304999da3f35ca1b0f52f78
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
