apiVersion: v2
type: application
name: podvm
description: |
  _podvm_ is a PoC/testing for running Firecracker in Kubernetes.
version: 0.0.0-alpha.8
appVersion: "v1.11.0"
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
