# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/test-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: registry-htpasswd
  labels:
    chart: registry

spec:
  concurrent: true

  bindings:
    - name: arguments
      value: >-
        --set=secrets.storage.accessKey.value=accessKey
        --set=secrets.storage.secretKey.value=secretKey
        --set=secrets.storage.endpoint.value=s3mock
        --set=secrets.storage.bucket.value=test
        --set=secrets.storage.region.value=test
        --set=secrets.storage.secure.value=false
        --set=secrets.auth.create=true
        --set=secrets.auth.htpasswd.value=user:$2y$10$3ZwL3ofEcgJYqpOjors2CO6UHKUX9TFB/g2/pE4IDCLKxex1Q5MTa

  steps:
    - name: Install S3Mock
      use:
        template: ../../_lib/s3mock.step.yaml
        with:
          bindings:
            - name: namespace
              value: ($namespace)

    - name: Install chart
      use:
        template: ../_lib/helm-install.step.yaml
        with:
          bindings:
            - name: arguments
              value: ($arguments)
            - name: namespace
              value: ($namespace)

    - name: Validate core installation
      use:
        template: ../_lib/validate-core-installation.step.yaml
        with:
          bindings:
            - name: namespace
              value: ($namespace)

    - name: Run push test
      use:
        template: ../_lib/test-push.step.yaml
        with:
          bindings:
            - name: namespace
              value: ($namespace)
            - name: INSECURE
              value: 'true'
            - name: REGISTRY_USER
              value: user
            - name: REGISTRY_PASSWORD
              value: Passw0rd1+

    - name: Run pull test
      use:
        template: ../_lib/test-pull.step.yaml
        with:
          bindings:
            - name: namespace
              value: ($namespace)
            - name: INSECURE
              value: 'true'
            - name: REGISTRY_USER
              value: user
            - name: REGISTRY_PASSWORD
              value: Passw0rd1+
