apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "scribe.config" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "scribe.labels" . | nindent 4 }}
data:
  config.yaml: |
    ---
    types:
    {{- range .Values.config }}
      {{- $apiVersion := .apiVersion }}
      {{- range .resources }}
      - apiVersion: {{ $apiVersion  }}
        kind: {{ .kind }}
      {{- end }}
    {{- end }}
