{{- if .Values.secret.create -}}
{{- $bitwardenHost := .Values.secret.bitwardenHost | required ".Values.secret.bitwardenHost is required." -}}
{{- $bitwardenUsername := .Values.secret.bitwardenUsername | required ".Values.secret.bitwardenUsername is required." -}}
{{- $bitwardenPassword := .Values.secret.bitwardenPassword | required ".Values.secret.bitwardenPassword is required." -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bitwarden-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "bitwarden-webhook.labels" . | nindent 8 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 8 }}
    {{- end }}
type: Opaque
stringData:
  BW_HOST: {{ $bitwardenHost }}
  BW_USERNAME: {{ $bitwardenUsername }}
  BW_PASSWORD: {{ $bitwardenPassword }}
{{- end }}
