{{- if .Values.backup.enabled -}}
{{- if .Values.backup.secret.create -}}
{{- $provider := .Values.database.provider }}
{{- if not (eq $provider "sqlite") }}
  {{- fail (printf "Invalid database: %s. .Values.database.provider must be 'sqlite' when backup is enabled." $provider) }}
{{- end }}
{{- if not (and .Values.backup.secret.replicas (gt (len .Values.backup.secret.replicas) 0)) }}
  {{- fail ".Values.backup.secret.replicas must have at least one item." }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pocket-id.backupSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
type: Opaque
stringData:
  {{- if .Values.backup.secret.accessKey }}
  ACCESS_KEY: "{{ .Values.backup.secret.accessKey }}"
  {{- end }}
  {{- if .Values.backup.secret.secretKey }}
  SECRET_KEY: "{{ .Values.backup.secret.secretKey }}"
  {{- end }}
  {{- range $i, $val := .Values.backup.secret.replicas }}
  {{- if $val.accessKey }}
  {{ printf "REPLICA_%d_ACCESS_KEY" $i }}: "{{ $val.accessKey }}"
  {{- end }}
  {{- if $val.secretKey }}
  {{ printf "REPLICA_%d_SECRET_KEY" $i }}: "{{ $val.secretKey }}"
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
