{{- if .Values.backup.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pocket-id.backupSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pocket-id.labels" . | nindent 4 }}
    {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  litestream.yaml: |
    addr: {{ .Values.backup.metricsAddress }}
    logging:
      level: {{ .Values.backup.logging.level }}
      type: {{ .Values.backup.logging.type }}
      stderr: {{ .Values.backup.logging.stderr }}
    {{- if .Values.backup.secret.accessKey }}
    access-key-id: "$ACCESS_KEY"
    {{- end }}
    {{- if .Values.backup.secret.secretKey }}
    secret-access-key: "$SECRET_KEY"
    {{- end }}
    dbs:
      - path: /data/pocket-id.db
        {{- if .Values.backup.monitorInterval }}
        monitor-interval: {{ .Values.backup.monitorInterval }}
        {{- end }}
        {{- if .Values.backup.checkpointInterval }}
        checkpoint-interval: {{ .Values.backup.checkpointInterval }}
        {{- end }}
        {{- if .Values.backup.busyTimeout }}
        busy-timeout: {{ printf .Values.backup.busyTimeout }}
        {{- end }}
        {{- if .Values.backup.minCheckpointPageCount }}
        min-checkpoint-page-count: {{ .Values.backup.minCheckpointPageCount }}
        {{- end }}
        {{- if .Values.backup.maxCheckpointPageCount }}
        max-checkpoint-page-count: {{ .Values.backup.maxCheckpointPageCount }}
        {{- end }}
        replicas:
    {{- range $i, $val := .Values.backup.secret.replicas }}
          - type: "{{ printf "$REPLICA_%d_TYPE" $i }}"
            path: "{{ printf "$REPLICA_%d_PATH" $i }}"
            access-key-id: "{{ printf "$REPLICA_%d_ACCESS_KEY" $i }}"
            secret-access-key: "{{ printf "$REPLICA_%d_SECRET_KEY" $i }}"
            region: "{{ printf "$REPLICA_%d_REGION" $i }}"
            bucket: "{{ printf "$REPLICA_%d_BUCKET" $i }}"
            endpoint: "{{ printf "$REPLICA_%d_ENDPOINT" $i }}"
            force-path-style: "{{ printf "$REPLICA_%d_FORCE_PATH_STYLE" $i }}"
            skip-verify: "{{ printf "$REPLICA_%d_SKIP_VERIFY" $i }}"
    {{- end }}
{{- end }}
