apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "omada-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omada-controller.labels" . | nindent 4 }}
data:
  OMADA_SSL_CERT_NAME: "tls.crt"
  OMADA_SSL_KEY_NAME: "tls.key"

  OMADA_MANAGE_HTTP_PORT: "{{ .Values.config.manageHttpPort | int | default 8088 }}"
  OMADA_MANAGE_HTTPS_PORT: "{{ .Values.config.manageHttpsPort | int | default 8043 }}"
  OMADA_PORTAL_HTTP_PORT: "{{ .Values.config.portalHttpPort | int | default 8888 }}"
  OMADA_PORTAL_HTTPS_PORT: "{{ .Values.config.portalHttpsPort | int | default 8843 }}"
  OMADA_PORT_ADOPT_V1: "{{ .Values.config.adoptV1Port | int | default 29812 }}"
  OMADA_PORT_APP_DISCOVERY: "{{ .Values.config.appDiscoveryPort | int | default 27001 }}"
  OMADA_PORT_DISCOVERY: "{{ .Values.config.discoveryPort | int | default 29810 }}"
  OMADA_PORT_MANAGER_V1: "{{ .Values.config.managerV1Port | int | default 29811 }}"
  OMADA_PORT_MANAGER_V2: "{{ .Values.config.managerV2Port | int | default 29814 }}"
  OMADA_PORT_TRANSFER_V2: "{{ .Values.config.transferV2Port | int | default 29815 }}"
  OMADA_PORT_RTTY: "{{ .Values.config.rttyPort | int | default 29816 }}"
  OMADA_PORT_UPGRADE_V1: "{{ .Values.config.upgradeV1Port | int | default 29813 }}"

  OMADA_PUID: "{{ .Values.config.puid | int | default 508 }}"
  OMADA_PGID: "{{ .Values.config.pgid | int | default 508 }}"
  OMADA_PUSERNAME: "{{ .Values.config.pusername | default "omada" }}"
  OMADA_PGROUP: "{{ .Values.config.pgroup | default "omada" }}"

  OMADA_ROOTLESS: "{{ .Values.config.rootless | ternary "true" "false" }}"
  OMADA_SHOW_SERVER_LOGS: "{{ .Values.config.showServerLogs | ternary "true" "false" }}"
  OMADA_SHOW_MONGODB_LOGS: "{{ .Values.config.showMongoDbLogs | ternary "true" "false" }}"
  OMADA_SKIP_USERLAND_KERNEL_CHECK: "{{ .Values.config.skipUserlandKernelCheck | ternary "true" "false" }}"
  OMADA_SMALL_FILES: "{{ .Values.config.smallFiles | ternary "true" "false" }}"
  OMADA_TLS_LEGACY_ENABLED: "{{ .Values.config.tlsLegacyEnabled | ternary "true" "false" }}"
  OMADA_TZ: "{{ .Values.config.timezone | default "Etc/UTC" }}"
