apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "omada-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "omada-controller.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "omada-controller.fullname" . }}
  replicas: 1
  {{- if .Values.updateStrategy }}
  {{- with .Values.updateStrategy }}
  updateStrategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "omada-controller.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "omada-controller.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "omada-controller.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      {{- if (and .Values.persistence.data.enabled (not (eq .Values.persistence.data.existingClaim ""))) }}
        - name: {{ include "omada-controller.pvcData" . }}
          persistentVolumeClaim:
            claimName: {{ include "omada-controller.pvcData" . }}
      {{- else if not .Values.persistence.data.enabled }}
        - name: {{ include "omada-controller.pvcData" . }}
          emptyDir: {}
      {{- end }}
      containers:
        - name: omada-controller
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: manage-http
              containerPort: {{ .Values.config.manageHttpPort }}
            - name: manage-https
              containerPort: {{ .Values.config.manageHttpsPort }}
            - name: portal-http
              containerPort: {{ .Values.config.portalHttpPort }}
            - name: portal-https
              containerPort: {{ .Values.config.portalHttpsPort }}
            - name: adopt-v1
              containerPort: {{ .Values.config.adoptV1Port }}
            - name: app-discovery
              containerPort: {{ .Values.config.appDiscoveryPort }}
            - name: discovery
              containerPort: {{ .Values.config.discoveryPort }}
            - name: manager-v1
              containerPort: {{ .Values.config.managerV1Port }}
            - name: manager-v2
              containerPort: {{ .Values.config.managerV2Port }}
            - name: transfer-v2
              containerPort: {{ .Values.config.transferV2Port }}
            - name: rtty
              containerPort: {{ .Values.config.rttyPort }}
            - name: upgrade-v1
              containerPort: {{ .Values.config.upgradeV1Port }}
          {{- if .Values.probes.enabled }}
          livenessProbe:
            {{ toYaml .Values.probes.livenessProbe | nindent 12}}
          readinessProbe:
            {{ toYaml .Values.probes.readinessProbe | nindent 12}}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "omada-controller.pvcData" . }}
              mountPath: /opt/tplink/EAPController/data
          envFrom:
            - configMapRef:
                name: {{ include "omada-controller.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- if (and .Values.persistence.data.enabled (eq .Values.persistence.data.existingClaim "")) }}
  volumeClaimTemplates:
    - metadata:
        name: {{ include "omada-controller.pvcData" . }}
        labels:
          {{- include "omada-controller.labels" . | nindent 10 }}
        {{- if .Values.persistence.data.annotations }}
        annotations:
          {{- toYaml .Values.persistence.data.annotations | nindent 10 }}
        {{- end }}
      spec:
        accessModes:
          - {{ .Values.persistence.data.accessMode }}
        resources:
          requests:
            storage: {{ .Values.persistence.data.size }}
        {{- if .Values.persistence.data.storageClass }}
        storageClassName: {{ .Values.persistence.data.storageClass }}
        {{- end }}
  {{- end }}
