apiVersion: v2
type: application
name: pocket-id
description: |
  pocket-id is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pocket-id/icon.png
version: 2.0.3
appVersion: "v2.5.0"
sources:
  - https://github.com/pocket-id/pocket-id
keywords:
  - idp
  - oidc
  - passkeys
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update docker.io/litestream/litestream docker tag to v0.5.11'
      links:
      - name: 'GitHub Issue #378'
        url: https://github.com/anza-labs/charts/issues/378
      - name: Commit cfdf92d
        url: https://github.com/anza-labs/charts/commit/cfdf92dbe2e7f1e6587ade8bc5e038507a4cdf6c
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
