apiVersion: v2
type: application
name: pocket-id
description: |
  pocket-id is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pocket-id/icon.png
version: 2.0.2
appVersion: "v2.5.0"
sources:
  - https://github.com/pocket-id/pocket-id
keywords:
  - idp
  - oidc
  - passkeys
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update docker.io/litestream/litestream docker tag to v0.5.10'
      links:
      - name: 'GitHub Issue #358'
        url: https://github.com/anza-labs/charts/issues/358
      - name: Commit c0880b9
        url: https://github.com/anza-labs/charts/commit/c0880b9ecc734a0d81830e9dce2b1b7a03b3174a
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
