apiVersion: v2
type: application
name: pocket-id
description: |
  pocket-id is a simple and easy-to-use OIDC provider that allows users to authenticate
  with their passkeys to your services.
home: https://pocket-id.org
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pocket-id/icon.png
version: 3.0.0
appVersion: "v2.16.0"
sources:
  - https://github.com/pocket-id/pocket-id
keywords:
  - idp
  - oidc
  - passkeys
  - sso
annotations:
  artifacthub.io/category: security
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update docker.io/litestream/litestream docker tag to v0.5.17'
      links:
      - name: 'GitHub Issue #453'
        url: https://github.com/anza-labs/charts/issues/453
      - name: Commit 46a6a84
        url: https://github.com/anza-labs/charts/commit/46a6a849be301fb0815f621fc700a5cff057bde0
    - kind: changed
      description: '**deps:** update ghcr.io/pocket-id/pocket-id docker tag to v2.14.0'
      links:
      - name: 'GitHub Issue #452'
        url: https://github.com/anza-labs/charts/issues/452
      - name: Commit 8988679
        url: https://github.com/anza-labs/charts/commit/89886790245eedda05dd9939cc67a62c5a6f941d
    - kind: changed
      description: '**deps:** update ghcr.io/pocket-id/pocket-id docker tag to v2.16.0'
      links:
      - name: 'GitHub Issue #472'
        url: https://github.com/anza-labs/charts/issues/472
      - name: Commit aafebcd
        url: https://github.com/anza-labs/charts/commit/aafebcd465bed267c89fbdc1b6907e06e4e79336
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
