{{- if .Values.telemetry.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pyoci.telemetryConfig" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyoci.labels" . | nindent 4 }}
stringData:
  {{ if not (quote .Values.telemetry.otlpEndpoint | empty) }}
  OTLP_ENDPOINT: "{{ .Values.telemetry.otlpEndpoint }}"
  {{ end }}
  {{ if not (quote .Values.telemetry.otlpAuth | empty) }}
  OTLP_AUTH: "{{ .Values.telemetry.otlpAuth }}"
  {{ end }}
  {{ if not (quote .Values.telemetry.deploymentEnvironment | empty) }}
  DEPLOYMENT_ENVIRONMENT: "{{ .Values.telemetry.deploymentEnvironment }}"
  {{ end }}
{{- end }}
