apiVersion: v1
kind: Service
metadata:
  name: {{ include "pyoci.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "pyoci.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "pyoci.selectorLabels" . | nindent 4 }}
