{{- if .Values.reboot.enabled }}
{{- $fullname := include "devenv.fullname" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullname }}-reboot
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devenv.labels" . | nindent 4 }}
{{- end }}
