{{- if and .Values.sshKeys.authorizedKeys (not .Values.sshKeys.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "devenv.sshKeysSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "devenv.labels" . | nindent 4 }}
stringData:
  authorized_keys: |
    {{- .Values.sshKeys.authorizedKeys | nindent 4 }}
{{- end }}
