# yaml-language-server: $schema=https://raw.githubusercontent.com/kyverno/chainsaw/main/.schemas/json/steptemplate-chainsaw-v1alpha1.json
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: StepTemplate
metadata:
  name: test-ldap
  labels:
    chart: glauth
spec:
  try:
    - apply:
        resource:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: test-ldap
            labels:
              charts.anza-labs.dev/test: glauth-ldap
          spec:
            template:
              metadata:
                labels:
                  charts.anza-labs.dev/test: glauth-ldap
              spec:
                restartPolicy: OnFailure
                containers:
                  - name: crane
                    image: ghcr.io/anza-labs/library/ldap-tools:latest
                    imagePullPolicy: IfNotPresent
                    command: ["/bin/sh", "-c"]
                    args:
                      - |
                        #!/bin/sh

                        set -eux

                        export LDAP_URI="ldap://${NAMESPACE}-glauth.${NAMESPACE}:3893"

                        ldapsearch -LLL -H "${LDAP_URI}" -D "${BINDDN}" -w "${PASSWD}" -x -b "${BASEDN}" "${FILTER}"

                        ldapsearch -LLL -H "${LDAP_URI}" -D "${BINDDN}" -w "${PASSWD}" -x -b "" -s base "+"

                        ldapsearch -LLL -H "${LDAP_URI}" -D "${BINDDN}" -w "${PASSWD}" -x -b "${BINDDN}" dn
                    env:
                      - name: NAMESPACE
                        value: ($namespace)
                      - name: BINDDN
                        value: ($BINDDN)
                      - name: BASEDN
                        value: ($BASEDN)
                      - name: PASSWD
                        value: ($PASSWD)
                      - name: FILTER
                        value: ($FILTER)
    - assert:
        timeout: 120s
        resource:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: test-ldap
          status:
            succeeded: 1
  catch:
    - describe:
        apiVersion: batch/v1
        kind: Job
        name: test-ldap
    - podLogs:
        namespace: ($namespace)
        selector: charts.anza-labs.dev/test=glauth-ldap
        tail: -1
