apiVersion: v2
type: application
name: hosted-control-plane
description: |
  _hosted-control-plane_ is a PoC/testing ground for any improvements that might
  reach Cluster API Control Plane Provider KinK manifests.
home: https://anza-labs.github.io/kink
version: 0.1.5
appVersion: "v1.32.3"
maintainers:
  - name: Mateusz Urbanek
    email: matueusz.urbanek.98@gmail.com
    url: http://linkedin.com/in/urbanekmateusz
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: ">=v1.16.0"
    condition: cert-manager.deploy
