{{- if .Values.configs.telemetry.create }}
---
{{- range $key, $value := .Values.configs.telemetry.otel }}
  {{- if not (hasPrefix "OTEL_" $key) }}
    {{- fail (printf ".Values.configs.telemetry.otel config key '%s' must start with 'OTEL_'." $key) }}
  {{- end }}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry.telemetryConfig" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configs.telemetry.otel }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
{{- if .Values.configs.registry.create }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "registry.config" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
data:
  config.yml: |
    version: 0.1
    health:
      storagedriver:
        enabled: true
        interval: 10s
        threshold: 3
    http:
      addr: 0.0.0.0:5000
      debug:
        addr: 0.0.0.0:5001
        prometheus:
          enabled: true
          path: /metrics
      headers:
        X-Content-Type-Options:
          - nosniff
    log:
      level: info
      accesslog:
        disabled: false
        formatter: json
    storage:
      cache:
        blobdescriptor: inmemory
      delete:
        enabled: false
      maintenance:
        uploadpurging:
          enabled: false
      tag:
        concurrencylimit: 8
      s3:
        rootdirectory: "/registry"
{{- end }}
