{{- if .Values.secrets.storage.create }}
{{- $accessKey := .Values.secrets.storage.accessKey.value -}}
{{- if not .Values.secrets.storage.accessKey.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.accessKey.value is required" $accessKey }}
{{- end }}
{{- $secretKey := .Values.secrets.storage.secretKey.value -}}
{{- if not .Values.secrets.storage.secretKey.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.secretKey.value is required" $secretKey }}
{{- end }}
{{- $region := .Values.secrets.storage.region.value -}}
{{- if not .Values.secrets.storage.region.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.region.value is required" $region }}
{{- end }}
{{- $endpoint := .Values.secrets.storage.endpoint.value -}}
{{- if not .Values.secrets.storage.endpoint.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.endpoint.value is required" $endpoint }}
{{- end }}
{{- $forcePathStyle := .Values.secrets.storage.forcePathStyle.value -}}
{{- if not .Values.secrets.storage.forcePathStyle.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.forcePathStyle.value is required" $forcePathStyle }}
{{- end }}
{{- $bucket := .Values.secrets.storage.bucket.value -}}
{{- if not .Values.secrets.storage.bucket.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.bucket.value is required" $bucket }}
{{- end }}
{{- $secure := .Values.secrets.storage.secure.value -}}
{{- if not .Values.secrets.storage.secure.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.secure.value is required" $secure }}
{{- end }}
{{- $v4Auth := .Values.secrets.storage.v4Auth.value -}}
{{- if not .Values.secrets.storage.v4Auth.valueFrom.optional }}
  {{- $_ := required ".Values.secrets.storage.v4Auth.value is required" $v4Auth }}
{{- end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.storageSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.storage.accessKey.valueFrom.key }}: {{ .Values.secrets.storage.accessKey.value | quote }}
  {{ .Values.secrets.storage.secretKey.valueFrom.key }}: {{ .Values.secrets.storage.secretKey.value | quote }}
  {{ .Values.secrets.storage.region.valueFrom.key }}: {{ .Values.secrets.storage.region.value | quote }}
  {{ .Values.secrets.storage.endpoint.valueFrom.key }}: {{ .Values.secrets.storage.endpoint.value | quote }}
  {{ .Values.secrets.storage.forcePathStyle.valueFrom.key }}: {{ .Values.secrets.storage.forcePathStyle.value | quote }}
  {{ .Values.secrets.storage.bucket.valueFrom.key }}: {{ .Values.secrets.storage.bucket.value | quote }}
  {{ .Values.secrets.storage.secure.valueFrom.key }}: {{ .Values.secrets.storage.secure.value | quote }}
  {{ .Values.secrets.storage.v4Auth.valueFrom.key }}: {{ .Values.secrets.storage.v4Auth.value | quote }}
{{- end }}
{{- if .Values.secrets.http.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.httpSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  REGISTRY_HTTP_SECRET: {{ .Values.secrets.http.value | quote }}
{{- end }}
{{- if .Values.secrets.auth.create }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "registry.authSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "registry.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.auth.htpasswd.valueFrom.key }}: |
    {{- .Values.secrets.auth.htpasswd.value | nindent 4}}
{{- end }}
