apiVersion: v2
name: scribe
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "v0.1.0"
maintainers:
  - name: Mateusz Urbanek
    email: matueusz.urbanek.98@gmail.com
    url: http://linkedin.com/in/urbanekmateusz
