apiVersion: v2
name: meta-chart
description: ''
type: application
version: 0.1.2
appVersion: "meta"
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz

