{{- if .Values.oidc.create -}}
  {{- $providerName := .Values.oidc.providerName | required ".Values.oidc.providerName is required." -}}
  {{- $clientId := .Values.oidc.clientId | required ".Values.oidc.clientId is required." -}}
  {{- $clientSecret := .Values.oidc.clientSecret | required ".Values.oidc.clientSecret is required." -}}
  {{- $authURL := .Values.oidc.authURL | required ".Values.oidc.authURL is required." -}}
  {{- $tokenURL := .Values.oidc.tokenURL | required ".Values.oidc.tokenURL is required." -}}
  {{- $redirectURL := .Values.oidc.redirectURL | required ".Values.oidc.redirectURL is required." -}}
  {{- $scope := .Values.oidc.scope | required ".Values.oidc.scope is required." -}}
  {{- $validateState := .Values.oidc.validateState | required ".Values.oidc.validateState is required." -}}
  {{- $usePKCE := .Values.oidc.usePKCE | required ".Values.oidc.usePKCE is required." -}}
  {{- $disableRegularLogin := .Values.oidc.disableRegularLogin | required ".Values.oidc.disableRegularLogin is required." -}}
  {{- $userInfoURL := .Values.oidc.userInfoURL | default "" -}}
  {{- $logOutURL := .Values.oidc.logOutURL | default "" -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lubelog.oidcSecret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lubelog.labels" . | nindent 4 }}
type: Opaque
stringData:
  OpenIDConfig__Name: {{ $providerName | quote }}
  OpenIDConfig__ClientId: {{ $clientId | quote }}
  OpenIDConfig__ClientSecret: {{ $clientSecret | quote }}
  OpenIDConfig__AuthURL: {{ $authURL | quote }}
  OpenIDConfig__TokenURL: {{ $tokenURL | quote }}
  OpenIDConfig__RedirectURL: {{ $redirectURL | quote }}
  OpenIDConfig__Scope: {{ $scope | quote }}
  OpenIDConfig__ValidateState: {{ $validateState | quote }}
  OpenIDConfig__UsePKCE: {{ $usePKCE  | quote }}
  OpenIDConfig__DisableRegularLogin: {{ $disableRegularLogin | quote }}
  OpenIDConfig__UserInfoURL: {{ $userInfoURL | quote }}
  OpenIDConfig__LogOutURL: {{ $logOutURL | quote }}
{{- end }}
