{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glauth.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  glauth.toml: |
    {{- if kindIs "string" .Values.secret.value }}
    {{- .Values.secret.value | nindent 4 }}
    {{- else }}
    {{- .Values.secret.value | toToml | nindent 4 }}
    {{- end }}
{{- end }}
