{{- if .Values.secret.create -}}
{{- $cfg := deepCopy .Values.secret.value -}}
{{- include "convertFloatsToInts" $cfg -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "glauth.secret" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "glauth.labels" . | nindent 4 }}
type: Opaque
stringData:
  config.cfg: |
    {{- $cfg | toToml | nindent 4 }}
{{- end }}
