name: Label autorelease PRs

on:
  pull_request:
    types:
      - closed

permissions:
  pull-requests: write
  contents: read

jobs:
  label-autorelease:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Label merged autorelease PR
        uses: actions/github-script@v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;

            const titleMatches = pr.title.startsWith("chore(main): release");
            const authorMatches = pr.user.login === "shanduur-auto";

            if (titleMatches && authorMatches) {
              const owner = context.repo.owner;
              const repo = context.repo.repo;
              const number = pr.number;

              await github.rest.issues.addLabels({
                owner,
                repo,
                issue_number: number,
                labels: ["autorelease: published"]
              });

              // Attempt to remove "autorelease: pending" if it exists
              try {
                await github.rest.issues.removeLabel({
                  owner,
                  repo,
                  issue_number: number,
                  name: "autorelease: pending"
                });
                console.log("Removed label: autorelease: pending");
              } catch (error) {
                if (error.status === 404) {
                  console.log("Label 'autorelease: pending' was not present.");
                } else {
                  throw error;
                }
              }

              console.log(`Labels updated on PR #${number}`);
            } else {
              console.log("PR does not match title and author conditions.");
            }
