name: release
on:
  push:
    branches:
      - main
permissions:
  contents: write
  pull-requests: write
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: fregante/setup-git-user@v2
      - uses: bitwarden/sm-action@v2
        with:
          access_token: ${{ secrets.BW_ACCESS_TOKEN }}
          base_url: https://vault.bitwarden.com
          secrets: |
            568fd648-901a-4161-85e4-b1c500b3cb94 > GPG_KEYRING_BASE64
            ffb60bb8-8422-4d3b-95a1-b20700fb5232 > GPG_PASSPHRASE
      - name: Prepare GPG key
        run: |
          ./hack/gpg.sh \
            "${GPG_KEYRING_BASE64}" \
            "${GPG_PASSPHRASE}" \
            "${GITHUB_ENV}"
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - id: releaser
        uses: helm/chart-releaser-action@v1
        env:
          CR_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          charts_dir: ./anza-labs
          config: .cr.yaml
