name: tests

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - "main"

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true
      - uses: helm/chart-testing-action@v2
      - run: |
          make update-repos
      - run: |
          ct lint \
            --target-branch ${{ github.event.repository.default_branch }} \
            --validate-chart-schema=false \
            --check-version-increment=false

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          make test
      - uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: 'charts/*/junit.xml'
          detailed_summary: true
          include_passed: false
          annotate_only: true
          group_reports: false

  e2e:
    runs-on: ubuntu-latest
    concurrency:
      group: >
        ${{
          github.event_name == 'pull_request'
            && format('pr-{0}', github.event.pull_request.number)
            || format('push-{0}', github.ref_name)
        }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: |
          make \
            cluster
      - run: |
          make \
            test-e2e \
            CHAINSAW_ARGS='--parallel=2 --report-format=JUNIT-STEP'
      - uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: 'chainsaw-report.xml'
          detailed_summary: true
          include_passed: true
          include_time_in_summary: true
          annotate_only: true
