name: tests

on:
  pull_request:
    branches: ["*"]
  push:
    branches:
      - "main"

jobs:
  chart-testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          check-latest: true
      - uses: helm/chart-testing-action@v2
      - run: |
          make update-repos
      - run: |
          ct lint \
            --target-branch ${{ github.event.repository.default_branch }} \
            --validate-chart-schema=false \
            --check-version-increment=false

  unittest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          make test

  e2e:
    runs-on: ubuntu-latest
    needs:
      - unittest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod
      - run: |
          make \
            cluster
      - run: |
          make \
            test-e2e
