apiVersion: v2
type: application
name: pyoci
description: |-
  Publish and install private python packages using OCI/docker registries.
home: https://pyoci.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pyoci/icon.jpg
version: "1.1.3"
appVersion: "v0.1.39"
sources:
  - https://github.com/AllexVeldman/pyoci
keywords:
  - oci-registry
  - docker
  - pyoci
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**install:** improve install docs'
      links:
      - name: 'GitHub Issue #399'
        url: https://github.com/anza-labs/charts/issues/399
      - name: Commit e8fdc56
        url: https://github.com/anza-labs/charts/commit/e8fdc5680642d4c2e304999da3f35ca1b0f52f78
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
