apiVersion: v2
type: application
name: pyoci
description: |-
  Publish and install private python packages using OCI/docker registries.
home: https://pyoci.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pyoci/icon.jpg
version: "1.0.3"
appVersion: "v0.1.38"
sources:
  - https://github.com/AllexVeldman/pyoci
keywords:
  - oci-registry
  - docker
  - pyoci
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: changed
      description: '**deps:** update ghcr.io/allexveldman/pyoci docker tag to v0.1.38'
      links:
      - name: 'GitHub Issue #345'
        url: https://github.com/anza-labs/charts/issues/345
      - name: Commit 9ca3038
        url: https://github.com/anza-labs/charts/commit/9ca30388fbe5c9e4f41f02708ef7871b0444ad68
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
