apiVersion: v2
type: application
name: pyoci
description: |-
  Publish and install private python packages using OCI/docker registries.
home: https://pyoci.com
icon: https://raw.githubusercontent.com/anza-labs/charts/main/charts/pyoci/icon.jpg
version: "1.1.1"
appVersion: "v0.1.38"
sources:
  - https://github.com/AllexVeldman/pyoci
keywords:
  - oci-registry
  - docker
  - pyoci
annotations:
  artifacthub.io/immutable: "true"
  artifacthub.io/changes: |-
    - kind: added
      description: add updateStrategy to multiple charts
      links:
      - name: Commit 87ce31e
        url: https://github.com/anza-labs/charts/commit/87ce31ef82f1553bf8bd74a1e9c294a56a0172dd
    - kind: changed
      description: generate docs and schemas
      links:
      - name: Commit f2ad0de
        url: https://github.com/anza-labs/charts/commit/f2ad0de519f6932484fd55ff647011942c4ac092
maintainers:
  - name: shanduur
    email: maturb@proton.me
    url: http://linkedin.com/in/urbanekmateusz
